version: '3'

services:
  modernapiapp:
    image: modernapiapp
    build:
      context: ./ModernApiApp
      dockerfile: Dockerfile
    environment:
      - ApiAppDatabaseServer=modernapiapp.data;
      - ApiAppDatabaseName=ModernApiAppDb;
      - ApiAppDatabaseUser=sa;
      - ApiAppDatabasePassword=Microsoft!1;
      - ASPNETCORE_ENVIRONMENT=Development
    expose:
      - "80"
    ports:
      - "5000:80"
    #extra hosts can be used for standalone SQL Server or services at the dev PC
    extra_hosts:
      - "DESKTOP-4GNBEL6:10.0.75.1"
    depends_on:
      - modernapiapp.data

  modernapiapp.data:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      - SA_PASSWORD=Microsoft!1
      - ACCEPT_EULA=Y
    ports:
      - "5434:1433"

  

